[package]
name = "clitools"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byte_prefix = "1.0.0"
colored = "2.1.0"
no_color = "0.1.0"
rand = "0.8.5"
clearscreen = "2.0.1"
